config/routes.rb
Rails.application.routes.draw do
  resources :save_files
  resources :games
  devise_for :users

  namespace :api do
    namespace :v1 do
      get '/profile', to: 'users#profile', as: 'user_profile'

      get '/games/lookup', to: 'games#lookup', as: 'game_lookup'
      resources :games do
        get '/save_files/latest', to: 'save_files#latest', as: 'save_files_latest'
        get '/save_files/lookup', to: 'save_files#lookup', as: 'save_file_lookup'
        resources :save_files
      end
    end
  end

  get '/profile', to: 'users#profile', as: 'user_profile'
  get '/profile/edit', to: 'users#edit', as: 'edit_user_profile'
  patch '/profile/edit', to: 'users#update', as: 'update_user_profile'
  put '/profile/edit', to: 'users#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "base#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :save_files, through: :games

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable, :timeoutable, :trackable

  before_create :set_api_key

  def account_active?
      return !self.is_disabled
  end

  def active_for_authentication?
    super && account_active?
  end

  def fullname
    return self.first_name if not self.first_name.blank? and self.last_name.blank?
    return self.last_name if not self.last_name.blank? and self.first_name.blank?

    return "#{self.first_name} #{self.last_name}" if not self.first_name.blank? and not self.last_name.blank?

    return self.email
  end

  def has_name?
    self.fullname != self.email
  end

  def generate_api_key
    loop do
      token = SecureRandom.hex(20)
      break token unless User.exists?(api_key: token)
    end
  end

  def set_api_key
    self.api_key = self.generate_api_key
  end

  def platforms
    tag_ids = ActsAsTaggableOn::Tagging.where(taggable_type: 'Game', taggable_id: self.games).pluck(:tag_id)
    ActsAsTaggableOn::Tag.where(id: tag_ids).order(:name)
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiController
  def profile
    render json: current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def profile
    @tags = current_user.games.tag_counts_on(:platforms)
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to user_profile_path }
      else
        format.html { render action: :edit }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/views/users/edit.html.erb
<h1><%= t(:editing_profile, name: current_user.fullname) %></h1>

<%= simple_form_for current_user, url: update_user_profile_path, method: :patch do |f| %>
    <%= f.input :first_name, value: current_user.first_name %>
    <%= f.input :last_name, value: current_user.last_name %>
    <%= f.input :email, value: current_user.email %>
    <%= f.button :submit, t(:save_changes) %>
<% end %>

app/views/users/profile.html.erb
<div class="row">
    <div class="col-md-4 order-md-2 mb-4">
        <h1>
        <%= current_user.fullname %>

        <% if current_user.has_name? %>
          <small class="text-muted"><%= current_user.email %></small>
        <% end %>
        </h1>
    
        <dl class="row">
        <dt class="col-sm-3"><%= t(:api_key) %></dt>
        <dd class="col-sm-9"><%= current_user.api_key %></dd>
        </dl>

        <h3><%= t(:actions) %></h3>
        <div class="d-flex justify-content-left">
        <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center"><%= link_to t(:edit_user_account), edit_user_profile_path %></li>
        <li class="list-group-item d-flex justify-content-between align-items-center"><%= link_to t(:change_password), edit_user_registration_path %></li>
        </ul>
        </div>
    </div>
</div>