config/routes.rb
Rails.application.routes.draw do
  resources :save_files
  resources :games
  devise_for :users

  namespace :api do
    namespace :v1 do
      get '/profile', to: 'users#profile', as: 'user_profile'

      get '/games/lookup', to: 'games#lookup', as: 'game_lookup'
      resources :games do
        get '/save_files/latest', to: 'save_files#latest', as: 'save_files_latest'
        get '/save_files/lookup', to: 'save_files#lookup', as: 'save_file_lookup'
        resources :save_files
      end
    end
  end

  get '/profile', to: 'users#profile', as: 'user_profile'
  get '/profile/edit', to: 'users#edit', as: 'edit_user_profile'
  patch '/profile/edit', to: 'users#update', as: 'update_user_profile'
  put '/profile/edit', to: 'users#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "base#index"
end

app/models/save_file.rb
class SaveFile < ApplicationRecord
  belongs_to :game
  has_one_attached :sram

  def full_name
    if not name.blank?
      name
    end
  end
end

app/controllers/api/v1/save_files_controller.rb
class Api::V1::SaveFilesController < Api::V1::ApiController
  before_action :set_game
  before_action :set_save_file, only: [:show, :edit, :update, :destroy]

  def index
    render json: @game.save_files
  end

  def show
    render json: @save_file
  end

  def lookup
    @save_file = @game.save_files.joins(sram_attachment: :blob).where(active_storage_blobs: {checksum: params[:checksum]}).first
    if not @save_file.blank?
      render json: @save_file
    else
      head :ok
    end
  end

  def latest
    @save_file = @game.save_files.order(mtime: :desc).first
    if not @save_file.blank?
      render json: @save_file
    else
      head :ok
    end
  end

  def create
    @save_file = SaveFile.new(save_file_params)
    @save_file.game = @game

    if @save_file.save
      render json: @save_file
    else
      render json: @save_file.errors, status: :unprocessable_entity
    end
  end

  def update
    if @save_file.update(save_file_params)
      render json: @save_file
    else
      render json: @save_file.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @save_file.destroy
    head :no_content
  end

private
  def set_game
    @game = current_user.games.find(params[:game_id])
  end

  def set_save_file
    @save_file = SaveFile.find(params[:id])
  end

  def save_file_params
    params.require(:save_file).permit(:name, :notes, :sram, :mtime)
  end

end

app/controllers/save_files_controller.rb
class SaveFilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_save_file, only: [:show, :edit, :update, :destroy]

  # GET /save_files
  # GET /save_files.json
  def index
    @save_files = current_user.save_files
  end

  # GET /save_files/1
  # GET /save_files/1.json
  def show
  end

  # GET /save_files/new
  def new
    @save_file = SaveFile.new
  end

  # GET /save_files/1/edit
  def edit
  end

  # POST /save_files
  # POST /save_files.json
  def create
    @save_file = SaveFile.new(save_file_params)

    respond_to do |format|
      if @save_file.save
        format.html { redirect_to @save_file, notice: 'Save file was successfully created.' }
        format.json { render :show, status: :created, location: @save_file }
      else
        format.html { render :new }
        format.json { render json: @save_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /save_files/1
  # PATCH/PUT /save_files/1.json
  def update
    respond_to do |format|
      if @save_file.update(save_file_params)
        format.html { redirect_to @save_file.game, notice: 'Save file was successfully updated.' }
        format.json { render :show, status: :ok, location: @save_file }
      else
        format.html { render :edit }
        format.json { render json: @save_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /save_files/1
  # DELETE /save_files/1.json
  def destroy
    @save_file.destroy
    respond_to do |format|
      format.html { redirect_to save_files_url, notice: 'Save file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_save_file
      @save_file = SaveFile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def save_file_params
      params.require(:save_file).permit(:name, :game_id, :notes, :sram, :mtime)
    end
end

app/helpers/save_files_helper.rb
module SaveFilesHelper
end

app/views/save_files/_form.html.erb
<%= simple_form_for(@save_file) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :game %>
    <%= f.input :notes %>
    <%= f.input :sram %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/save_files/_info.html.erb
<h1>
  <%= save_file.name %>
</h1>

<p>
  <strong>Game:</strong>
  <%= save_file.game.name %>
</p>

<p>
  <strong>Notes:</strong>
  <%= save_file.notes %>
</p>

<p>
<strong><%= t(:last_modified) %></strong>
<%= t(:time_ago, time_ago: time_ago_in_words(save_file.mtime)) %>
</p>

<p>
  <strong><%= t(:checksum) %>:</strong>
  <%= save_file.sram.checksum  if not save_file.sram.attachment.nil? %>
</p>

<p>
  <strong><%= t(:sram_file) %>:</strong>
  <%= link_to save_file.sram.filename, url_for(save_file.sram) if not save_file.sram.attachment.nil? %>
</p>

<%= link_to 'Edit', edit_save_file_path(save_file) %>

app/views/save_files/edit.html.erb
<h1>Editing Save File</h1>

<%= render 'form', save_file: @save_file %>

<%= link_to 'Back', @save_file.game %>

app/views/save_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Save Files</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Game</th>
      <th>SRAM File</th>
      <th><%= t(:checksum) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @save_files.each do |save_file| %>
      <tr>
        <td><%= save_file.name %></td>
        <td><%= link_to save_file.game.name, save_file.game %></td>
        <td><%= link_to save_file.sram.filename, url_for(save_file.sram) if not save_file.sram.attachment.nil? %></td>
        <td><%= save_file.sram.checksum  if not save_file.sram.attachment.nil? %></td>
        <td><%= link_to 'Show', save_file %></td>
        <td><%= link_to 'Edit', edit_save_file_path(save_file) %></td>
        <td><%= link_to 'Destroy', save_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Save File', new_save_file_path %>

app/views/save_files/new.html.erb
<h1>New Save File</h1>

<%= render 'form', save_file: @save_file %>

<%= link_to 'Back', save_files_path %>

app/views/save_files/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: 'info', locals: { save_file: @save_file } %>