config/routes.rb
Rails.application.routes.draw do
  resources :save_files
  resources :games
  devise_for :users

  namespace :api do
    namespace :v1 do
      get '/profile', to: 'users#profile', as: 'user_profile'

      get '/games/lookup', to: 'games#lookup', as: 'game_lookup'
      resources :games do
        get '/save_files/latest', to: 'save_files#latest', as: 'save_files_latest'
        get '/save_files/lookup', to: 'save_files#lookup', as: 'save_file_lookup'
        resources :save_files
      end
    end
  end

  get '/profile', to: 'users#profile', as: 'user_profile'
  get '/profile/edit', to: 'users#edit', as: 'edit_user_profile'
  patch '/profile/edit', to: 'users#update', as: 'update_user_profile'
  put '/profile/edit', to: 'users#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "base#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:sram_percolator) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <%= link_to t(:sram_percolator), root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav mr-auto">

            <% if not user_signed_in? %>
            <li class="nav-item active">
              <%= link_to t(:signup_login), new_user_session_path, class: 'nav-link' %>
            </li>
            <% else %>
            <li class="nav-item active">
              <%= link_to fa_icon('gamepad', text: t(:games)), games_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to fa_icon('id-card', text: t(:profile)), user_profile_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to fa_icon('sign-out', text: t(:logout)), destroy_user_session_path, class: 'nav-link' %>
            </li>
            <% end %>

          </ul>
      
          <form class="form-inline my-2 my-lg-0" action="<%= url_for games_path %>" >
            <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="<%= params[:q] %>">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>

    </nav>

    <main role="main" class="col-12 col-md-9 container-fluid">
      <div id="content">
        <%= yield %>
      </div>
    </main>

  </body>
</html>